"use client";
import {motion,useScroll,useTransform} from "framer-motion";
import {useRef,useState} from "react";
const agents=[["SCOUT","Find signals","Prospects, conversations, market and ecosystem signals."],["SENTINEL","Watch conditions","Wallets, contracts, communities and operational thresholds."],["ANALYST","Reason with context","Classify events, connect context and propose next actions."],["OPERATOR","Act with limits","Run approved workflow steps; sensitive actions stay gated."],["CONCIERGE","Respond safely","Handle known support and community requests from approved knowledge."],["ARCHIVIST","Prove the run","Capture decisions, outputs, approvals and an audit trail."]];
const workflows=[["Community → CRM","Detect a high-intent conversation → enrich context → draft response → request approval → log outcome."],["On-chain signal → Ops","Watch a contract event → classify → correlate with internal rules → notify operator → archive evidence."],["Lead → Website","Qualify an inbound lead → map requirements → generate a scoped workflow → hand off for review."]];
function SignalCore(){const ref=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll({target:ref,offset:["start end","end start"]});const r=useTransform(scrollYProgress,[0,1],[0,220]);return <div ref={ref} className="core-wrap"><motion.div style={{rotate:r}} className="orbit orbit-a"/><motion.div style={{rotate:r}} className="orbit orbit-b"/><div className="core"><span/><span/><span/></div><div className="core-label">SIGNAL<br/><b>CORE_01</b></div></div>}
export default function Home(){const [active,setActive]=useState(0);return <main>
<header className="nav"><a className="brand" href="#"><i/>AGENTFORGE</a><nav><a href="#agents">Agents</a><a href="#workflows">Workflows</a><a href="#control">Control</a></nav><a className="nav-cta" href="#map">Map workflow ↗</a></header>
<section className="hero"><div className="hero-grid"/><div className="hero-copy"><p className="eyebrow">AI OPERATIONS / WEB3</p><h1>Turn fragmented<br/><em>activity into action.</em></h1><p className="lede">A controlled crew of AI agents for the work that sits between your community, on-chain signals, research and operations.</p><div className="actions"><a className="button primary" href="#map">Map my workflow <span>↗</span></a><a className="button ghost" href="#agents">See the system</a></div></div><SignalCore/><div className="hero-foot"><span>SCROLL TO EXPLORE</span><span>01 / 06</span></div></section>
<section className="statement"><p className="eyebrow">THE PROBLEM</p><h2>Web3 does not run in one inbox.</h2><div className="problem-grid"><div>COMMUNITY<br/><b>Messages. Requests. Intent.</b></div><div>ON-CHAIN<br/><b>Events. Wallets. Conditions.</b></div><div>OPERATIONS<br/><b>Research. CRM. Treasury.</b></div><div>HUMANS<br/><b>Judgement. Approval. Accountability.</b></div></div></section>
<section id="agents" className="agents"><div className="section-head"><div><p className="eyebrow">THE CREW</p><h2>Six roles.<br/>One operating layer.</h2></div><p>AgentForge separates discovery, reasoning and execution so automation can move quickly without pretending humans are optional.</p></div><div className="agent-grid">{agents.map((a,i)=><motion.button whileHover={{y:-5}} key={a[0]} className={active===i?"agent active":"agent"} onClick={()=>setActive(i)}><span>0{i+1}</span><strong>{a[0]}</strong><small>{a[1]}</small><p>{a[2]}</p><b className="arrow">↗</b></motion.button>)}</div></section>
<section id="workflows" className="workflow"><div className="section-head"><div><p className="eyebrow">WORKFLOW ANATOMY</p><h2>Signal → Reason → Act → Report</h2></div><p>Show the run, surface the approval moment, and leave evidence behind.</p></div><div className="pipeline"><div className="pipe-line"/>{["SIGNAL","REASON","APPROVAL","ACT","REPORT"].map((x,i)=><motion.div initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.1}} className="node" key={x}><span>0{i+1}</span><strong>{x}</strong><small>{["event detected","context assembled","human gate","approved step","audit trail"][i]}</small></motion.div>)}</div></section>
<section className="use"><div className="section-head"><div><p className="eyebrow">USE CASES</p><h2>Start with the bottleneck.</h2></div><p>Map the repetitive work around the valuable work. Keep sensitive decisions in the loop.</p></div><div className="case-list">{workflows.map((w,i)=><div className="case" key={w[0]}><span>0{i+1}</span><div><h3>{w[0]}</h3><p>{w[1]}</p></div><b>↗</b></div>)}</div></section>
<section id="control" className="control"><div className="control-visual"><div className="rings"/><div className="lock">⌁</div></div><div><p className="eyebrow">CONTROL LAYER</p><h2>Autonomy is useful.<br/><em>Unbounded autonomy isn't the product.</em></h2><ul><li><b>Human gates</b><span>Approval before sensitive actions.</span></li><li><b>Scoped permissions</b><span>Each agent gets only the tools its job needs.</span></li><li><b>Traceable runs</b><span>Inputs, decisions and outputs stay inspectable.</span></li><li><b>Recovery paths</b><span>Pause, retry, escalate or hand back to a human.</span></li></ul></div></section>
<section id="map" className="mapper"><div><p className="eyebrow">WORKFLOW MAPPER</p><h2>Describe the work.<br/><em>We map the system.</em></h2><p>Tell us where requests arrive, what gets repeated and where a human must approve. The first map should make the hidden workflow visible.</p><a className="button primary" href="mailto:hello@agentforge-web3.com?subject=AgentForge%20workflow%20map">Start a workflow map ↗</a></div><div className="terminal"><div className="term-top"><span>AGENTFORGE / MAPPER</span><i>● ● ●</i></div><div className="term-body"><p><b>$</b> ingest workflow</p><p className="dim">channel: community</p><p className="dim">signal: qualified intent</p><p><b>→</b> route to <strong>SCOUT</strong></p><p><b>→</b> context via <strong>ANALYST</strong></p><p><b>→</b> approval gate <strong>HUMAN</strong></p><p><b>→</b> execute <strong>OPERATOR</strong></p><p className="success">✓ trace saved / run_0017</p><span className="cursor"/></div></div></section>
<footer><div className="brand"><i/>AGENTFORGE</div><p>Controlled AI agents for Web3 operations.</p><div><a href="#agents">Agents</a><a href="#workflows">Workflows</a><a href="#control">Control</a></div></footer>
</main>}